[project]
name = "kvsp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kvsp7", email = "kvsp7.ai@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
kvsp-server = "kvsp_server:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
